server:
  port: ${SERVER_PORT:8097}
  tomcat:
    threads:
      max: 10
      min-spare: 2

spring:
  config:
    activate:
      on-profile: prod
  devtools:
    add-properties: true
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        query:
          plan_cache_max_size: 16
          plan_parameter_metadata_max_size: 16
        temp:
          use_jdbc_metadata_defaults: false