spring:
  config:
    activate:
      on-profile: prod
  devtools:
    add-properties: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true